server:
  error:
    include-message: always
    include-binding-errors: always

h2-server:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true

feign:
  httpclient:
    disable-ssl-validation: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

